name: Daily News Update

on:
  schedule:
    - cron: "0 6 * * *"   # every day 6 AM UTC
  workflow_dispatch:       # allow manual run

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python daily_gemini_news.py

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add index.html news_*.html
          git commit -m "Daily news update" || echo "No changes"
          git push
